---
title: "Rawson_Exam_3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(tidyr)
library(dplyr)
library(transformr)
library(sf)
library(broom)
```

# Step One:
  # Load and clean FacultySalaries_1995.csv
```{r echo=TRUE, message=FALSE, warning=FALSE, include=TRUE}
dat <- read_csv("./FacultySalaries_1995.csv")
dat <- dat %>% 
  pivot_longer(cols = c("AvgFullProfSalary", "AvgAssocProfSalary", "AvgAssistProfSalary"),
               names_to = "Rank",
               values_to = "Salary") %>% 
  pivot_longer(cols = c("AvgFullProfComp", "AvgAssocProfComp", "AvgAssistProfComp"),
               names_to = "Rank_Comp",
               values_to = "Compensation") %>% 
  pivot_longer(cols = c("NumFullProfs", "NumAssocProfs", "NumAssistProfs", "NumInstructors"),
               names_to = "Rank_Num",
               values_to = "Staff_Number") %>% 
  mutate(Rank = case_when(Rank == "AvgFullProfSalary" ~ "Full",
                          Rank == "AvgAssocProfSalary" ~ "Assoc",
                          Rank == "AvgAssistProfSalary" ~ "Assist"))
dat <- dat[!(dat$Tier=="VIIB"), ]
```

# Create, save, and export fig1
```{r echo=TRUE, message=FALSE, warning=FALSE, include=TRUE}
dat %>% 
  ggplot(aes(x=Rank,y=Salary)) +
  geom_boxplot(aes(fill=Rank)) +
  facet_wrap(~Tier) +
  theme_minimal() +
  theme(legend.key.size = unit(1, "cm"),
        legend.title = element_text(size = 19, color = "black"),
        legend.text = element_text(size = 13, color = "black"),
        axis.text.x = element_text(angle = 65, size = 13, color = "black"),
        axis.text.y = element_text(size = 13, color = "black"),
        axis.title.x = element_text(size = 19, color = "black"),
        axis.title.y = element_text(size = 19, color = "black"),
        strip.text.x = element_text(size = 13, color = "black"))
ggsave("./RAWSON_Fig_1.jpg")
```

# STEP Two: 
  # Exported ANOVA file and created table showing rank, tier, and state
```{r echo=TRUE, message=FALSE, warning=FALSE, include=TRUE}
mod1 <- glm(data = dat, 
            formula = Salary ~ State + Tier + Rank)
summary(mod1)
anova(mod1)
sink("./Salary_ANOVA_Summary.txt")
anova(mod1)
sink(NULL)
```

# STEP Three:
  # Load and clean/tidy Juniper_Oils.csv
```{r echo=TRUE, message=FALSE, warning=FALSE, include=TRUE}
dat2 <- read_csv("./Juniper_Oils.csv")
dat2 <- dat2 %>% 
  pivot_longer(cols = c("alpha-pinene","para-cymene","alpha-terpineol","cedr-9-ene",
                        "alpha-cedrene","beta-cedrene","cis-thujopsene","alpha-himachalene",
                        "beta-chamigrene","cuparene","compound 1","alpha-chamigrene",
                        "widdrol","cedrol","beta-acorenol","alpha-acorenol","gamma-eudesmol",
                        "beta-eudesmol","alpha-eudesmol","cedr-8-en-13-ol","cedr-8-en-15-ol",
                        "compound 2","thujopsenal"),
               names_to = "ChemicalID",
               values_to = "Concentration")
```

# STEP Four: 
  # Create, save, and export fig2
```{r echo=TRUE, message=FALSE, warning=FALSE, include=TRUE}
dat2 %>% 
  ggplot(aes(x=YearsSinceBurn, y=Concentration)) +
  geom_smooth(method = loess) +
  facet_wrap(~ChemicalID, scales = "free_y") +
  theme_minimal() +
  labs(x = "Years Since Burn",
       title = "Concentration by Chemical") +
  theme(plot.title = element_text(hjust = 0.5))
ggsave("./RAWSON_Fig_2.jpg")
```

# STEP Five: 
  # Use a generalized linear model to find chemicals that are significant
```{r echo=TRUE, message=FALSE, warning=FALSE, include=TRUE}
mod2 <- glm(data = dat2, formula = Concentration ~ ChemicalID * YearsSinceBurn)
mod2_sum <- summary(mod2)
tt <- tidy(mod2)
ttss <- tt[c(tt$p.value <= 0.05), ]
```